### ISSUE TITLE
Plugin not working

### ISSUE THREAD

**Issue by gussandy** [AdamBrodzinski/validate-form#1]
Hi Adam, just added the plugin to my project testing it out but, nothing seems to work even though I've followed the instructions to the letter. Your help will be appreciated. Thanks.

**Comment by AdamBrodzinski** [comment]
Doh! I've forgotten to update the readme code. In order to prevent the package from trying to validate any form, the form needs a class of "validate" in order for the events to trigger.

Apologies for wasting your time grinding away trying to make I work! I'll update the readme this weekend.

Thanks!
PS... I'll be adding more input validations over the next couple of weeks.

**Comment by gussandy** [comment]
Thanks Adam.

**Comment by AdamBrodzinski** [comment]
@gussandy Just updated the readme with https://github.com/AdamBrodzinski/validate-form/commit/92e61135cba0acf3b4af08a61bac16f4495dfc9b .

Thanks again! Hoping to add more validation inputs this Sunday... have you ran into any limitations yet?
